// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;

namespace HHY.Models.KeyVisual
{
    public partial class RequestKeyVisuals
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Url { get; set; }
        public string ImgUrl { get; set; }
        public DateTime PublishDate { get; set; }
        public DateTime DownDate { get; set; }
        public IFormFile file { get; set; }
    }
}