// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace HHY.Models.Member
{
    public partial class RequestMembers
    {
        public int ID { get; set; }

        [Display(Name = "帳號")]
        [EmailAddress]
        [Required(ErrorMessage = "帳號必填")]

        public string Email { get; set; }
        [Display(Name = "密碼")]
        [Required(ErrorMessage = "密碼必填")]

        public string Password { get; set; }
        [Display(Name = "姓名")]
        [Required(ErrorMessage = "姓名必填")]
        public string Name { get; set; }

        [Display(Name = "帳號是否啟用")]
        public bool IsVerify { get; set; }

        [Display(Name = "確認密碼")]
        public string CheckPassword { get; set; }
    }
}