// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace HHY.Models
{
    public partial class Abouts
    {
        public int ID { get; set; }
        public string Content { get; set; }
        public DateTime PublishDate { get; set; }
        public DateTime DownDate { get; set; }
        public string Title { get; set; }
    }
}