// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace HHY.Models
{
    public partial class HHYContext : DbContext
    {
        public HHYContext()
        {
        }

        public HHYContext(DbContextOptions<HHYContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Abouts> Abouts { get; set; }
        public virtual DbSet<Blogs> Blogs { get; set; }
        public virtual DbSet<HotSaleProducts> HotSaleProducts { get; set; }
        public virtual DbSet<KeyVisuals> KeyVisuals { get; set; }
        public virtual DbSet<Members> Members { get; set; }
        public virtual DbSet<Menu> Menu { get; set; }
        public virtual DbSet<ProductBanners> ProductBanners { get; set; }
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<ReportFile> ReportFile { get; set; }
        public virtual DbSet<SeasonalActivities> SeasonalActivities { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("ProductVersion", "2.2.0-rtm-35687");

            modelBuilder.Entity<Abouts>(entity =>
            {
                entity.Property(e => e.Title)
                    .IsRequired()
                    .HasDefaultValueSql("(N'')");
            });

            modelBuilder.Entity<Blogs>(entity =>
            {
                entity.Property(e => e.Title).IsRequired();

                entity.Property(e => e.VideoUrl).IsRequired();
            });

            modelBuilder.Entity<Members>(entity =>
            {
                entity.Property(e => e.Email).IsRequired();

                entity.Property(e => e.Name).IsRequired();

                entity.Property(e => e.Password).IsRequired();
            });

            modelBuilder.Entity<Menu>(entity =>
            {
                entity.Property(e => e.Title).IsRequired();

                entity.Property(e => e.Url).IsRequired();
            });

            modelBuilder.Entity<Products>(entity =>
            {
                entity.Property(e => e.ID).ValueGeneratedNever();

                entity.Property(e => e.BuyUrl).IsUnicode(false);

                entity.Property(e => e.Name).IsRequired();

                entity.Property(e => e.Price).HasColumnType("decimal(18, 2)");

                entity.Property(e => e.SalePrice).HasColumnType("decimal(18, 2)");

                entity.Property(e => e.Weight)
                    .IsRequired()
                    .HasDefaultValueSql("(N'')");
            });

            modelBuilder.Entity<ReportFile>(entity =>
            {
                entity.Property(e => e.FileName).IsRequired();

                entity.Property(e => e.Path).IsRequired();
            });

            modelBuilder.Entity<SeasonalActivities>(entity =>
            {
                entity.Property(e => e.Title).IsRequired();
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}