// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace HHY.Models
{
    public partial class Products
    {
        public Guid ID { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
        public decimal SalePrice { get; set; }
        public string Information { get; set; }
        public DateTime PublishDate { get; set; }
        public DateTime DownDate { get; set; }
        public string ImgUrl { get; set; }
        public bool IsPromotion { get; set; }
        public string Weight { get; set; }
        public string BuyUrl { get; set; }
        public string SubTitle { get; set; }
        public string Standard { get; set; }
    }
}