// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace HHY.Models
{
    public partial class ReportFile
    {
        public string Path { get; set; }
        public string FileName { get; set; }
        public Guid ProductID { get; set; }
        public int ID { get; set; }
    }
}