// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;

namespace HHY.Models.Blog
{
    public partial class RequestBlog
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string VideoUrl { get; set; }
        public string ImgUrl { get; set; }
        public DateTime PublishDate { get; set; }
        public DateTime DownDate { get; set; }
        public string Content { get; set; }
        public IFormFile file { get; set; }

        public string SubContent { get; set; }

        public string Type { get; set; }
    }
}